name: deployment
on:
  pull_request:
jobs:
  main:
    name: yarn-simple
    runs-on: ubuntu-latest
    env:
      PRODUCTION_KEY: "App6276"
      PRODUCTION_ID: 6276
      ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-node@v2
        with:
          node-version: 18.17
      - name: test
        run: |
          curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.2
          export PATH="$HOME/.yarn/bin:$PATH"
          yarn global add zapier-platform-cli@11.2.0
          yarn install
          yarn run lint
          yarn run zapier-test
          echo "{\"deployKey\": $ZAPIER_DEPLOY_KEY}" > .zapierrc
          echo "{\"id\": $PRODUCTION_ID,\"key\": $RODUCTION_KEY}" > .zapierapprc
          echo 'Zendesk Sell (6276)' | yarn run zapier-link
          yarn run zapier-push --skip-npm-install
